version: '3.8'

services:
  frontend:
    build: 
      context: ./bezkoder-ui
      args:
        - REACT_APP_API_URL=http://18.207.123.74:8080
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://18.207.123.74:8080 
    depends_on:
      - backend

  backend:
    build: ./bezkoder-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=ecommerce
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: